### PR TITLE
Fix - Multiple Project Search results

### LINKED ISSUE #9: Compensate bad-sorting in project-search
I have a template, that searches for ACTINT00001.1.1 - unfortunately, SAP returns a list in the "wrong" order

ACTINT00001.1.10
ACTINT00001.1.1
ACTINT00001.1.12

the correct entry is not on the first place.

Image

Proposal:

- either store more search terms (does not work out)
- loop over the result-set, to find the correct match

### PR DESCRIPTION
**Pull request by meesha01**
Changes:
- Loop through project search results
- Extract the Project ID
- Compare with saved ID
- If matches, click

### CODE REVIEW

File: scripts/field-manipulator.js [hunk 1]
```diff
@@ -101,7 +101,14 @@ async function setProject(projectId){
         const searchResultListItem = await waitForElement(
             `#${PROJECT_SEARCH_RESULT_LIST_ID} > li:not(#${PROJECT_SEARCH_NO_DATA_LI_ID})`
         );
-        simulateClick(searchResultListItem);
+        const projectList = searchResultListItem.parentElement;
+
+        for(const listItem of projectList.children) {
```
Comment (roka-actico) [inline scripts/field-manipulator.js:106]: I'd add a check: if projectList.children is empty, then show a message like: It seems that you are (no longer) allowed for this project.

**Review by roka-actico — APPROVED** [review]

**Comment by roka-actico** [comment]
works like a charm

File: scripts/field-manipulator.js (hunk 1 above)
Comment (meesha01) [reply scripts/field-manipulator.js]: done :)
